Sinaq_MVC/MVC_Sinaq/Areas/Admin/ViewModels/Destination/DestinationCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Sinaq.Areas.Admin.ViewModels.Destination
{
    public class DestinationCreateVM
    {
        [Required]
        public IFormFile Image { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public float Price { get; set; }
        [Required, Range(0, 5)]
        public float Rate { get; set; }
    }
}

Sinaq_MVC/MVC_Sinaq/Areas/Admin/ViewModels/Destination/DestinationListItemVM.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Sinaq.Areas.Admin.ViewModels.Destination
{
    public class DestinationListItemVM
    {
        public int Id { get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public float Price { get; set; }
        [Required, Range(0, 5)]
        public float Rate { get; set; }
    }
}

Sinaq_MVC/MVC_Sinaq/Areas/Admin/ViewModels/Destination/DestinationUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Sinaq.Areas.Admin.ViewModels.Destination
{
    public class DestinationupdateVM
    {
        [Required]
        public IFormFile Image { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public float Price { get; set; }
        [Required, Range(0, 5)]
        public float Rate { get; set; }
    }
}

Sinaq_MVC/MVC_Sinaq/Models/Destination.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Sinaq.Models
{
    public class Destination
    {
        public int Id{ get; set; }
        [Required]
        public string Image { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public float Price { get; set; }
        [Required,Range(0,5)]
        public float Rate { get; set; }

    }
}

Sinaq_MVC/MVC_Sinaq/Models/ErrorViewModel.cs
namespace MVC_Sinaq.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sinaq_MVC/MVC_Sinaq/ViewModels/Destination/DestinationListItemUserVM.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Sinaq.ViewModels.Destination
{
    public class DestinationListItemUserVM
    {
        [Required]
        public string Image { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public float Price { get; set; }
        [Required, Range(0, 5)]
        public float Rate { get; set; }
    }
}

Sinaq_MVC/MVC_Sinaq/Areas/Admin/Controllers/DestinationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Sinaq.Areas.Admin.ViewModels.Destination;
using MVC_Sinaq.Contexts;
using MVC_Sinaq.Helpers;
using MVC_Sinaq.Models;
using System.Linq;

namespace MVC_Sinaq.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DestinationController : Controller
    {
            TravelingDBContext _db { get; }

        public DestinationController(TravelingDBContext db)
        {
            _db = db;
        }

        public async Task< IActionResult> Index()
        {
            var data = await _db.Destinations.Select(s => new DestinationListItemVM
            {
                Image = s.Image,
                Title = s.Title,
                Id = s.Id,
                Price = s.Price,
                Rate = s.Rate,
            }).ToListAsync();
            return View(data) ;
        }
        public  IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DestinationCreateVM vm)
        {
            if(!ModelState.IsValid)
            {
                return View(vm);
            }
            Destination destination = new Destination 
            {
                Image = vm.Image.FileUploadasync(PathExtension.FileUpload).Result,
                Title = vm.Title,
                Price = vm.Price,
                Rate = vm.Rate,
            };
            await _db.Destinations.AddAsync(destination);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
           var data= await _db.Destinations.FindAsync(id);
            _db.Destinations.Remove(data);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }

}

Sinaq_MVC/MVC_Sinaq/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Sinaq.Areas.Admin.ViewModels.Destination;
using MVC_Sinaq.Contexts;
using MVC_Sinaq.Models;
using MVC_Sinaq.ViewModels.Destination;
using System.Diagnostics;

namespace MVC_Sinaq.Controllers
{
    public class HomeController : Controller
    {
       
       TravelingDBContext _db { get; }

        public HomeController(TravelingDBContext db)
        {
            _db = db;
        }

        public async Task< IActionResult >Index()
        {
            var data = await _db.Destinations.Select(s => new DestinationListItemUserVM
            {
                Image = s.Image,
                Title = s.Title,
                Price = s.Price,
                Rate = s.Rate,
            }).ToListAsync();
            return View(data);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sinaq_MVC/MVC_Sinaq/Areas/Admin/Views/Destination/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model DestinationCreateVM
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input type="text" class="form-control" id="titleid" placeholder="Title">

    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input type="text" class="form-control" id="Imageid" placeholder="Image" accept="image/*">
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input type="number" class="form-control" id="Priceid" placeholder="Price">
    </div>
    <div class="form-group">
        <label asp-for="Rate">Rate select</label>
        <select class="form-control" id="RateId">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div>
    <div>
        <button class="btn btn-succes">Submit</button>
    </div>
  
</form>

Sinaq_MVC/MVC_Sinaq/Areas/Admin/Views/Destination/Index.cshtml
@{
    ViewData["Title"] = "Admin Page";
}
@model List<DestinationListItemVM>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<div>
    <a class="btn" asp-action="Create" asp-controller="Destination"> Create</a>
    <table class ="table table-bordered" id="dataTable" width="100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Price</th>
                <th>Image</th>
                <th>Rate</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(DestinationListItemVM item in Model)
               {
            <tr>
                    <td>@item.Id</td>
                    <td>@item.Title</td>
                    <td>@item.Price</td>
                    <td><img width="250" src="/@item.Image"/></td>
                    <td>@item.Rate</td>
                    <td><a class= "btn" asp-action="Update" asp-controller="Destination" asp-route-id="@item.Id">Update</a></td>
                    <td><a class="btn" asp-action="Delete" asp-controller="Destination" asp-route-id="@item.Id">Delete</a></td>
            </tr>
               }
        </tbody>
        
    </table>
</div>
  

Sinaq_MVC/MVC_Sinaq/Areas/Admin/Views/Destination/Update.cshtml
@{
    ViewData["Title"] = "Create";
}
@model DestinationCreateVM
@* 

<div class="card shadow mb-4">
   
    <div class="card-body">
        <form  method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="Title">Title</label>
                <input id="Title" type="text" class="form-control" name="Title">
            </div>
            <div class="form-group">
                <label asp-for="Image">Image</label>
                <input asp-for="Image" accept="image/*" class="form-control">
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Rate">Rate</label>
                <input type="text" id="Rate" name="Rate" class="form-control">
            </div> 
            <div class="form-group">
                <label for="Price">Price</label>
                <input type="text" id="Price" name="Price" class="form-control">
            </div>

            <button class="btn btn-success">Submit!</button>
        </form>
    </div>
</div> *@






<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title">Title</label>
            <input type="text" class="form-control" name="Title" id="Title" placeholder="Title">

    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
            <input asp-for="Image" class="form-control" id="Image" accept="image/*">
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
            <input type="number" class="form-control" name="Price" id="Price" placeholder="Price">
    </div>

        <div class="form-group">
            <label asp-for="Rate">Rate</label>
            <input type="number" id="Rate" name="Rate" class="form-control">
        </div>
        @*  <div class="form-group">
        <label asp-for="Rate">Rate select</label>
            <select class="form-control" name="Rate" id="Rate">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
    </div> *@
        <button class="btn btn-succes">Submit</button>
  
</form>

Sinaq_MVC/MVC_Sinaq/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Destination</title>

    <!-- Custom fonts for this template-->
    <link href="~/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin Panel<sup></sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Destination">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Destination</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">



            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>



                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->

            <!-- End of Main Content -->
                @RenderBody()
            </div> <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Your Website 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin/js/demo/chart-area-demo.js"></script>
    <script src="~/Admin/js/demo/chart-pie-demo.js"></script>

</body>

</html>

Sinaq_MVC/MVC_Sinaq/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <!-- Author -->
    <meta name="author" content="Themes Industry">
    <!-- description -->
    <meta name="description" content="MegaOne is a highly creative, modern, visually stunning and Bootstrap responsive multipurpose studio and portfolio HTML5 template with 8 ready home page demos.">
    <!-- keywords -->
    <meta name="keywords" content="Creative, modern, clean, bootstrap responsive, html5, css3, portfolio, blog, studio, templates, multipurpose, one page, corporate, start-up, studio, branding, designer, freelancer, carousel, parallax, photography, studio, masonry, grid, faq">
    <!-- Page Title -->
    <title>Travelling | MegaOne HTML5 Template</title>
    <!-- Favicon -->
    <link rel="icon" href="~/vendor/img/favicon.ico">
    <!-- Bundle -->
    <link rel="stylesheet" href="~/vendor/css/bundle.min.css">
    <!-- Plugin Css -->
    <link rel="stylesheet" href="~/vendor/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/vendor/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendor/css/swiper.min.css">
    <link rel="stylesheet" href="~/vendor/css/wow.css">
    <!-- Slider Settings -->
    <link rel="stylesheet" href="~/vendor/css/LineIcons.min.css">
    <link rel="stylesheet" href="~/travelling/css/settings.css">
    <!-- Style Sheet -->
    <link rel="stylesheet" href="~/travelling/css/style.css">
    <link rel="stylesheet" href="~/travelling/css/datepicker.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body data-offset="50" data-spy="scroll" data-target=".navbar">
    <!-- Preloader -->
    <div class="preloader">
        <div class="center">
            <div class="loader">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
    <!-- Preloader End -->
    <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-top-default fixed-top navbar-fixed-top">
            <!--Side Menu Button-->
            <div class="container">
                <a class="navbar-brand scroll" href="#home">
                    <img src="~/travelling/img/logo.png" alt="logo">
                </a>
                <!--Nav Links-->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item  active">
                            <a class="nav-link scroll" href="#home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  scroll" href="#destinations">Destinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#gallery">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#testimonials">Testimonials</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Container End -->
            <a href="javascript:void(0)" class="sidemenu_btn link" id="sidemenu_toggle">
                <span></span>
                <span></span>
                <span></span>
            </a>
            <a class="number">
                <p>+1 631 123 4567 </p>
            </a>
        </nav>
        <!-- Navbar End -->
        <!-- Side-Nav Start -->
        <div class="side-menu side-menu-opacity">
            <div class="bg-overlay"></div>
            <div class="inner-wrapper">
                <a class="image scroll" href="#home">
                    <img src="~/travelling/img/side-menu.png" alt="image">
                </a>
                <span class="btn-close" id="btn_sideNavClose"><i></i><i></i></span>
                <nav class="side-nav w-100">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  scroll" href="#destinations">Destinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#gallery">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#testimonials">Testimonials</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll" href="#contact">Contact</a>
                        </li>
                    </ul>
                </nav>
                <div class="side-menu-footer">
                    <div class="social-icons">
                        <ul>
                            <li>
                                <a href="#" class="hover"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li><a href="#" class="hover"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="hover"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#" class="hover"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                    <p class="copywrite text-left">&#169; 2020 MegaOne. <br>Made With Love by Themesindustry.</p>
                </div>
            </div>
        </div>
        <a id="close_side_menu" href="javascript:void(0);"></a>
        <!-- Side-Nav End -->
    </header>
    <!-- Header End -->
    <!--Slider Section Start-->

            @RenderBody()
    <!-- Contact section Start-->
    <section class="contact-section" id="contact">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-6 col-md-12 col-sm-12 text-section wow fadeInLeft" data-wow-delay="400ms">
                    <h5 class="subheading">Lorem ipsum dolor sit amet consectetur</h5>
                    <h2 class="heading">Megaone Travels</h2>
                    <p class="text">123 Stree New York City , United States Of America.</p>
                    <p class="text">Office Telephone : 001 01085379709<br>Mobile : 001 63165370895 </p>
                    <p class="text">Email : admin@website.com<br>Inquiries : email@website.com</p>
                    <p class="text">Mon-Fri: 9am to 6pm</p>
                    <div class="social-icons">
                        <ul>
                            <li>
                                <a class="facebook-hover wow fadeInUp" data-wow-delay="400ms" href="#.">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                            </li>
                            <li>
                                <a class="twitter-hover wow fadeInDown" data-wow-delay="400ms" href="#.">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a class="google-plus-hover wow fadeInUp" data-wow-delay="400ms" href="#.">
                                    <i class="fab fa-google-plus-g"></i>
                                </a>
                            </li>
                            <li>
                                <a class="linked-in-hover wow fadeInDown" data-wow-delay="400ms" href="#.">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            </li>
                            <li>
                                <a class="instagram-hover wow fadeInUp" data-wow-delay="400ms" href="#.">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 form-section wow fadeInRight" data-wow-delay="400ms">
                    <form class="contact-form" id="contact-form-data">
                        <div class="row">
                            <div class="col-12" id="result"></div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" id="quote_name" type="email" placeholder="Your Name" required="" name="userName">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="quote_email" type="email" placeholder="Email Address*" required="" name="userEmail">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="subject" type="text" placeholder="Subject" required="" name="userSubject">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Write your message here" name="userMessage" rows="7" cols="50"></textarea>
                                </div>
                            </div>
                            <div class="button-center">
                                <a href="JavaScript:void(0);" class="btn button btn-rounded green-btn btn-hvr-blue contact_btn">
                                    Send Message
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Container End -->
    </section>
    <!-- Contact section End -->
    <!--Scroll Top Start-->
    <span class="scroll-top-arrow"><i class="fas fa-angle-up"></i></span>
    <!--Scroll Top End-->
    </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- JavaScript -->
    <script src="~/vendor/js/bundle.min.js"></script>
    <!-- Plugin Js -->
    <script src="~/vendor/js/jquery.fancybox.min.js"></script>
    <script src="~/vendor/js/owl.carousel.min.js"></script>
    <script src="~/vendor/js/swiper.min.js"></script>
    <script src="~/vendor/js/wow.min.js"></script>
    <!-- custom script -->
    <script src="~/vendor/js/contact_us.js"></script>
    <script src="~/travelling/js/datepicker.js"></script>
    <script src="~/travelling/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>